<?php

return [
    'genders' => [
        'Male',
        'Female',
    ],
    'notice_periods' => [
        'Available immediately',
        '1 week',
        '2 weeks',
        '30 days',
        '60 days',
        '90 days',
        'Negotiable',
    ],
    'relocation_options' => [
        'Yes',
        'No',
    ],
    'job_industries' => [
        'Administration',
        'Construction',
        'Customer Service',
        'Education',
        'Engineering',
        'Finance',
        'Healthcare',
        'Human Resources',
        'Information Technology',
        'Legal',
        'Logistics',
        'Marketing',
        'Procurement & Supply Chain',
        'Sales',
        'Other',
    ],
    'employment_types' => [
        'Permanent',
        'Contract',
        'Temporary',
        'Internship',
        'Part-time',
    ],
    'education_levels' => [
        'Matric',
        'Certificate',
        'Diploma',
        'Bachelor Degree',
        'Honours Degree',
        'Master Degree',
        'Doctorate',
        'Other',
    ],
    'candidate_document_types' => [
        'cv' => 'CV',
        'qualification' => 'Qualification',
        'drivers_licence' => 'Driver\'s Licence',
        'certification' => 'Certification',
        'identity_document' => 'Identity Document',
        'other' => 'Other',
    ],
    'provinces' => [
        'Eastern Cape',
        'Free State',
        'Gauteng',
        'KwaZulu-Natal',
        'Limpopo',
        'Mpumalanga',
        'Northern Cape',
        'North West',
        'Western Cape',
    ],
];
